// <auto-generated />
using System;
using BookyPets.Infrastructure.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookyPets.Infrastructure.Migrations
{
    [DbContext(typeof(BookyPetsDbContext))]
    [Migration("20260222104807_AddingPet")]
    partial class AddingPet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BookyPets.Domain.PetAggregate.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FavouriteGenre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("_experience")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Experience");

                    b.HasKey("Id");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("BookyPets.Domain.ReaderAggregate.Reader", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_bookIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("BookIds");

                    b.Property<string>("_petIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PetIds");

                    b.Property<string>("_questIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("QuestIds");

                    b.HasKey("Id");

                    b.ToTable("Readers");
                });
#pragma warning restore 612, 618
        }
    }
}
