// <auto-generated />
using System;
using BookyPets.Infrastructure.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookyPets.Infrastructure.Migrations
{
    [DbContext(typeof(BookyPetsDbContext))]
    [Migration("20260308172550_AddRoles")]
    partial class AddRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BookyPets.Domain.BookAggregate.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookyPets.Domain.BookAggregate.Progress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("_readerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ReaderId");

                    b.HasKey("Id");

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("BookyPets.Domain.PetAggregate.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FavouriteGenre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("_experience")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Experience");

                    b.HasKey("Id");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("BookyPets.Domain.ReaderAggregate.Reader", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_bookIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("BookIds");

                    b.Property<string>("_passwordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("_petIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PetIds");

                    b.Property<string>("_progressIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ProgressIds");

                    b.Property<string>("_roles")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Roles");

                    b.HasKey("Id");

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("BookyPets.Domain.SessionAggregate.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("PagesRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("_bookId")
                        .HasColumnType("TEXT")
                        .HasColumnName("BookId");

                    b.Property<string>("_genre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Genre");

                    b.Property<Guid?>("_petId")
                        .HasColumnType("TEXT")
                        .HasColumnName("PetId");

                    b.Property<Guid>("_progressId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ProgressId");

                    b.Property<Guid>("_readerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ReaderId");

                    b.Property<DateTime>("_startTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartTime");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
